apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-pr-env
  labels:
    app: argocd-pr-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-pr-env
  template:
    metadata:
      labels:
        app: argocd-pr-env
    spec:
      containers:
        - name: argocd-pr-env
          image: rmiguel/argocd-pr-env:37-c034ccfc13eb5fa6f3021201a30d4cd951ee850f
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Dquarkus.http.host=0.0.0.0"
