replicaCount: 2

image:
  repository: rmiguel/argocd-pr-env
  tag: "40-4711259be614b39a47f2adba1de146269858ce5e"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
