name: Build and Push Quarkus App

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-publish-quarkus-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'     
      - name: Compile Quarkus app
        run: |
          mvn clean package

      - name: verify artifact
        run: pwd ; ls -la; ls -la target ; ls -lh target/quarkus-app-1.0.0-SNAPSHOT.jar
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}